name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./shared-components
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint || npx eslint src --ext .ts,.tsx

      - name: Run tests
        run: npm test

      - name: Upload test results (if using Jest)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: shared-components/jest-results.xml
        continue-on-error: true
